from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

css='''\n/* Austria map v2 — isolated from legacy region styles */\n.austria-map-v2{position:relative;width:100%;max-width:980px;margin:26px auto 18px;aspect-ratio:2.25/1;min-height:360px}.austria-map-v2 svg{position:absolute;inset:0;width:100%;height:100%;display:block;overflow:visible}.austria-map-v2 .country{fill:#eef3f7;stroke:#aebdca;stroke-width:3;vector-effect:non-scaling-stroke}.austria-map-v2 .region-map-btn{position:absolute!important;z-index:2;display:block!important;min-width:106px;max-width:145px;border:1px solid #cad5df!important;border-radius:14px!important;background:rgba(255,255,255,.97)!important;color:#17324d!important;padding:9px 11px!important;font:inherit!important;font-size:12px!important;font-weight:720!important;line-height:1.2!important;text-align:center!important;cursor:pointer!important;box-shadow:0 8px 22px rgba(21,45,68,.10)!important;transform:translate(-50%,-50%)!important;transition:.18s ease!important}.austria-map-v2 .region-map-btn:hover{box-shadow:0 10px 26px rgba(21,45,68,.16)!important;transform:translate(-50%,-53%)!important}.austria-map-v2 .region-map-btn.active{background:#111!important;color:#fff!important;border-color:#111!important}.austria-map-v2 .region-map-btn span{display:block!important;margin-top:3px!important;font-size:10px!important;font-weight:600!important;color:#6a7580!important}.austria-map-v2 .region-map-btn.active span{color:#ddd!important}.austria-map-v2 .region-map-btn.zero{opacity:.62}.austria-map-v2 .reset{left:10%;top:8%;transform:none!important;min-width:128px}.austria-map-v2 .reset:hover{transform:translateY(-2px)!important}.austria-map-v2 .vor{left:9%;top:55%}.austria-map-v2 .tir{left:27%;top:66%}.austria-map-v2 .sal{left:43%;top:47%}.austria-map-v2 .oo{left:54%;top:29%}.austria-map-v2 .noe{left:72%;top:31%}.austria-map-v2 .vie{left:84%;top:23%}.austria-map-v2 .bur{left:88%;top:54%}.austria-map-v2 .sty{left:66%;top:68%}.austria-map-v2 .kar{left:49%;top:79%}.map-help{font-size:13px;color:#70747a;margin:10px 0 0;max-width:900px}@media(max-width:760px){.austria-map-v2{aspect-ratio:auto;min-height:0;display:grid;grid-template-columns:1fr 1fr;gap:9px}.austria-map-v2 svg{position:relative;grid-column:1/-1;height:190px}.austria-map-v2 .region-map-btn{position:relative!important;left:auto!important;top:auto!important;transform:none!important;min-width:0!important;max-width:none!important;width:100%!important;min-height:56px}.austria-map-v2 .region-map-btn:hover{transform:none!important}.austria-map-v2 .reset{grid-column:1/-1}}\n'''
if 'Austria map v2' not in s:
    s=s.replace('</style>',css+'</style>',1)

block='''<div class="region-visual"><div class="region-visual-head"><h3>Keress magyar közösséget Ausztria térképén</h3><p>Kattints egy tartományra. A szám azt mutatja, hány külön bejegyzést közöl ott jelenleg a Központi Szövetség hivatalos tagszervezeti oldala.</p></div><div class="austria-map-v2" id="regionMap" aria-label="Ausztria tartományai – tagszervezeti szűrő"><svg viewBox="0 0 1000 440" role="img" aria-label="Ausztria stilizált térképe" preserveAspectRatio="xMidYMid meet"><path class="country" d="M48,235 L92,201 L155,205 L201,178 L265,191 L316,160 L371,166 L420,128 L482,139 L525,103 L590,117 L644,99 L705,122 L758,116 L802,145 L858,151 L908,184 L949,195 L927,238 L892,259 L876,302 L821,307 L783,335 L724,328 L681,360 L617,347 L571,382 L510,365 L455,390 L399,359 L344,365 L292,335 L232,340 L190,307 L130,298 L91,267 Z"/></svg><button class="region-map-btn reset active" data-region="Mind" type="button">Egész Ausztria <span>29 szervezet</span></button><button class="region-map-btn vor" data-region="Vorarlberg" type="button">Vorarlberg <span>2</span></button><button class="region-map-btn tir" data-region="Tirol" type="button">Tirol <span>5</span></button><button class="region-map-btn sal" data-region="Salzburg" type="button">Salzburg <span>1</span></button><button class="region-map-btn oo" data-region="Felső-Ausztria" type="button">Felső-Ausztria <span>4</span></button><button class="region-map-btn noe zero" data-region="Alsó-Ausztria" type="button">Alsó-Ausztria <span>0</span></button><button class="region-map-btn vie" data-region="Bécs" type="button">Bécs <span>10</span></button><button class="region-map-btn bur" data-region="Burgenland" type="button">Burgenland <span>3</span></button><button class="region-map-btn sty" data-region="Stájerország" type="button">Stájerország <span>4</span></button><button class="region-map-btn kar zero" data-region="Karintia" type="button">Karintia <span>0</span></button></div><p class="map-help">Mind a 9 osztrák tartomány látható. A 0 azt jelenti, hogy a Központi Szövetség jelenlegi hivatalos tagszervezeti oldalán nincs külön, az adott tartományhoz sorolt bejegyzés.</p></div>'''
pattern=r'<div class="region-visual"><div class="region-visual-head"><h3>Keress magyar közösséget Ausztria térképén</h3>.*?</div><input id="search"'
m=re.search(pattern,s,re.S)
if not m:
    raise SystemExit('map block not found')
s=s[:m.start()]+block+'<input id="search"'+s[m.end():]
p.write_text(s,encoding='utf-8')
