from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'class="region-visual"' in s:
    raise SystemExit(0)
css='''\n.region-visual{margin:30px 0 22px;padding:24px;border:1px solid #e0e0e0;border-radius:24px;background:linear-gradient(180deg,#fff,#f4f7fa)}.region-visual-head{margin-bottom:18px}.region-visual-head h3{margin:0;font-size:24px;letter-spacing:-.03em}.region-visual-head p{margin:5px 0 0;color:#666;font-size:14px}.austria-region-grid{display:grid;grid-template-columns:repeat(12,1fr);grid-template-rows:repeat(3,76px);gap:8px}.region-map-btn{border:0;border-radius:17px;background:#e8eef5;color:#17324d;font:inherit;font-weight:700;font-size:13px;cursor:pointer;transition:.18s ease;display:flex;align-items:center;justify-content:center;text-align:center;padding:8px;box-shadow:inset 0 0 0 1px rgba(10,75,143,.08)}.region-map-btn:hover{transform:translateY(-2px);background:#dce8f4}.region-map-btn.active{background:#111!important;color:#fff}.region-map-btn[data-region="Vorarlberg"]{grid-column:1/3;grid-row:2}.region-map-btn[data-region="Tirol"]{grid-column:3/6;grid-row:2/4}.region-map-btn[data-region="Salzburg"]{grid-column:6/8;grid-row:2}.region-map-btn[data-region="Felső-Ausztria"]{grid-column:7/10;grid-row:1}.region-map-btn[data-region="Stájerország"]{grid-column:8/11;grid-row:2/4}.region-map-btn[data-region="Burgenland"]{grid-column:11/13;grid-row:2/4}.region-map-btn[data-region="Bécs"]{grid-column:10/12;grid-row:1;background:#dbe9f7}.region-map-btn[data-region="Mind"]{grid-column:1/4;grid-row:1;background:#f0f0f0;color:#333}.region-count-mini{font-weight:500;font-size:11px;opacity:.7;margin-left:5px}@media(max-width:720px){.region-visual{padding:18px}.austria-region-grid{grid-template-columns:1fr 1fr;grid-template-rows:none}.region-map-btn{grid-column:auto!important;grid-row:auto!important;min-height:54px}}\n'''
s=s.replace('</style>',css+'</style>',1)
html='''<div class="region-visual"><div class="region-visual-head"><h3>Hol keresel magyar közösséget?</h3><p>Kattints egy tartományra, és csak az ott működő szervezetek jelennek meg.</p></div><div class="austria-region-grid" id="regionMap"><button class="region-map-btn active" type="button" data-region="Mind">Mind</button><button class="region-map-btn" type="button" data-region="Vorarlberg">Vorarlberg <span class="region-count-mini">2</span></button><button class="region-map-btn" type="button" data-region="Tirol">Tirol <span class="region-count-mini">5</span></button><button class="region-map-btn" type="button" data-region="Salzburg">Salzburg <span class="region-count-mini">1</span></button><button class="region-map-btn" type="button" data-region="Felső-Ausztria">Felső-Ausztria <span class="region-count-mini">4</span></button><button class="region-map-btn" type="button" data-region="Stájerország">Stájerország <span class="region-count-mini">4</span></button><button class="region-map-btn" type="button" data-region="Burgenland">Burgenland <span class="region-count-mini">2</span></button><button class="region-map-btn" type="button" data-region="Bécs">Bécs <span class="region-count-mini">10</span></button></div></div>'''
target='<input id="search" class="search"'
assert target in s
s=s.replace(target,html+target,1)
hook="searchEl.addEventListener('input',render);"
assert hook in s
js="searchEl.addEventListener('input',render);const regionMap=document.getElementById('regionMap');if(regionMap){regionMap.addEventListener('click',e=>{const b=e.target.closest('.region-map-btn');if(!b)return;active=b.dataset.region;regionMap.querySelectorAll('.region-map-btn').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.r===active));render();});filtersEl.addEventListener('click',()=>regionMap.querySelectorAll('.region-map-btn').forEach(x=>x.classList.toggle('active',x.dataset.region===active)));}"
s=s.replace(hook,js,1)
p.write_text(s,encoding='utf-8')
