const stateNames={wien:"Bécs",niederoesterreich:"Alsó-Ausztria",burgenland:"Burgenland / Őrvidék",oberoesterreich:"Felső-Ausztria",steiermark:"Stájerország",salzburg:"Salzburg",tirol:"Tirol",vorarlberg:"Vorarlberg",kaernten:"Karintia"};
let db={organizations:[],states:[]},events=[],activeState="";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmtDate=s=>{if(!s)return"";const d=new Date(s);return Number.isNaN(d)?s:new Intl.DateTimeFormat("hu-AT",{dateStyle:"long",timeStyle:s.includes("T")?"short":undefined}).format(d)};
function counts(){return db.organizations.reduce((a,o)=>(a[o.state]=(a[o.state]||0)+1,a),{})}
function renderMapCounts(){const c=counts();document.querySelectorAll(".austria-map button").forEach(b=>{b.title=`${stateNames[b.dataset.state]} – ${c[b.dataset.state]||0} szervezet`;b.classList.toggle("active",b.dataset.state===activeState)})}
function renderOrgs(){const q=(document.querySelector("#orgSearch").value||"").toLocaleLowerCase("hu");const list=db.organizations.filter(o=>(!activeState||o.state===activeState)&&(!q||[o.name,o.city,o.type,o.intro].join(" ").toLocaleLowerCase("hu").includes(q)));document.querySelector("#orgGrid").innerHTML=list.map(o=>`<article class="card"><div class="meta">${esc(stateNames[o.state])} · ${esc(o.city)} · ${esc(o.type)}</div><h3>${esc(o.name)}</h3><p>${esc(o.intro)}</p><div class="links"><a href="szervezet.html?id=${encodeURIComponent(o.id)}">Bemutatkozás →</a>${o.website?`<a href="${esc(o.website)}" target="_blank" rel="noopener external">Weboldal ↗</a>`:""}${o.facebook?`<a href="${esc(o.facebook)}" target="_blank" rel="noopener external">Facebook ↗</a>`:""}${o.instagram?`<a href="${esc(o.instagram)}" target="_blank" rel="noopener external">Instagram ↗</a>`:""}</div></article>`).join("");const c=counts();document.querySelector("#stateSummary").textContent=activeState?`${stateNames[activeState]}: ${c[activeState]||0} nyilvántartott szervezet / programgazda`:`${db.organizations.length} szervezet és programgazda, 9 tartományban`;renderMapCounts()}
function mapsLinks(address){if(!address)return"";const q=encodeURIComponent(address);return `<a href="https://www.google.com/maps/dir/?api=1&destination=${q}" target="_blank" rel="noopener external">Google Maps útvonal ↗</a><a href="https://maps.apple.com/?daddr=${q}" target="_blank" rel="noopener external">Apple Maps ↗</a>`}
function renderEvents(){const st=document.querySelector("#eventState").value,q=(document.querySelector("#eventSearch").value||"").toLocaleLowerCase("hu"),now=new Date();const list=events.filter(e=>(!e.endDate||new Date(e.endDate)>=now)&&(!st||e.state===st)&&(!q||[e.name,e.organizer,e.city,e.venue].join(" ").toLocaleLowerCase("hu").includes(q))).sort((a,b)=>String(a.startDate).localeCompare(String(b.startDate)));document.querySelector("#eventGrid").innerHTML=list.map(e=>`<article class="event"><div class="date">${esc(fmtDate(e.startDate))}</div><h3>${esc(e.name)}</h3><p><b>${esc(e.organizer||"")}</b>${e.venue||e.city?`<br>${esc([e.venue,e.address||e.city].filter(Boolean).join(" · "))}`:""}</p><div class="event-links">${e.sourceUrl?`<a href="${esc(e.sourceUrl)}" target="_blank" rel="noopener external">Esemény forrása ↗</a>`:""}${mapsLinks(e.address)}</div></article>`).join("");document.querySelector("#eventEmpty").hidden=!!list.length}
function bind(){document.querySelectorAll(".austria-map button").forEach(b=>b.addEventListener("click",()=>{activeState=activeState===b.dataset.state?"":b.dataset.state;renderOrgs();document.querySelector("#szervezetek").scrollIntoView({behavior:"smooth"})}));document.querySelector("#allStates").addEventListener("click",()=>{activeState="";renderOrgs()});document.querySelector("#orgSearch").addEventListener("input",renderOrgs);document.querySelector("#eventState").addEventListener("change",renderEvents);document.querySelector("#eventSearch").addEventListener("input",renderEvents)}
async function init(){const [o,e]=await Promise.all([fetch("data/organizations.json",{cache:"no-store"}).then(r=>r.json()),fetch("data/events.json",{cache:"no-store"}).then(r=>r.json()).catch(()=>({events:[]}))]);db=o;events=e.events||[];document.querySelector("#eventState").innerHTML+=[...db.states].map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");bind();renderOrgs();renderEvents()}
init();